### ISSUE TITLE
Error al exportar la epg

### ISSUE THREAD

**Issue by llorens89** [Paco8/plugin.video.orange.spain#9]
Hola!
No consigo que el add-on exporte la epg para usarla con IPTV Simple Client.

La lista de canales sí la tengo y se reproduce con PVR, pero la epg me está devolviendo error en cada intento.

Error Type: <class 'TypeError'>
                                                   Error Contents: 'NoneType' object is not callable
                                                   Traceback (most recent call last):
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.orange.spain/default.py", line 7, in <module>
                                                       run()
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.orange.spain/resources/lib/plugin.py", line 653, in run
                                                       router(params)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.orange.spain/resources/lib/plugin.py", line 605, in router
                                                       export_epg_now()
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.orange.spain/resources/lib/plugin.py", line 548, in export_epg_now
                                                       o.export_epg_to_xml(epg_filename)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.orange.spain/resources/lib/orange.py", line 1341, in export_epg_to_xml
                                                       start = datetime.strptime(e['start'], "%Y-%m-%dT%H:%M:%SZ").strftime("%Y%m%d%H%M%S +0000")
                                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                   TypeError: 'NoneType' object is not callable
                                                   -->End of Python script error report<--

**Comment by Paco8** [comment]
Lo acabo de mirar, y a mí no me pasa.
Prueba a borrar el fichero epg.json que está en `userdata/addon_data/plugin.video.orange.spain` a ver si es que se he descargado mal.
